#!/bin/bash
set -e
#set -x

if ! git diff-index --quiet HEAD --; then
    echo "there are uncommitted changes, please commit first."
    exit 2
fi

git checkout gh-pages

cp dist/index.html index.html
cp dist/dojo/dojo.js dojo/dojo.js
cp dist/dojo/nls/dojo_en-us.js dojo/nls/dojo_en-us.js
cp dist/dojo/nls/dojo_ROOT.js dojo/nls/dojo_ROOT.js
cp dist/app/resources/app.css app/resources/app.css
cp dist/dijit/nls/loading.js dijit/nls/loading.js
cp dist/dijit/nlc/common.js dijit/nls/common.js

if ! git diff-index --quiet HEAD --; then
    git commit -am "synced gh-pages from latest build on master"
    echo "you may want to run git push --all now."
else
    echo "there are no changes, wasting my time useless idiot?"
fi

git checkout master
